#!/usr/bin/env node
var program = require('commander');
var _ = require('lodash');

// var z = require('./lib');
var z = require('zenaton-javascript');
var StartCommand =  z.StartCommand;
var StopCommand = z.StopCommand;
var StatusCommand = z.StatusCommand;

program
   .version('0.0.1');

program
    .option('--boot [boot]', 'Define location of your boot file')
    .option('--env [env]', 'Define location of your .env file')
    .command('start')
    .description('Start Zenaton worker')
    .action(function() {
        (new StartCommand()).execute(program.env, program.boot);
    });

program
    .option('--env [env]', 'Define location of your .env file')
    .command('stop')
    .description('Stop the listening of Zenaton executable for this app/environment/language')
    .action(function() {
        (new StopCommand()).execute(program.env);
    });


program
    .command('status')
    .description('List all the subscribed application of a worker.')
    .action(function() {
        (new StatusCommand().execute());
    });

 program.parse(process.argv);
