#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');
var Configuration = require('./lib/Worker').Configuration;

program
   .version('0.0.1');

 program
   .command('start <.env> <source>')
   .description('start a worker with .env credentials and source file')
   .action(function(env, source) {

       if (! fs.existsSync(env)) {
            console.log('Error! Unabled to find '+ env +' file.');
            return
       }

       if (! fs.existsSync(source)) {
            console.log('Error! Unabled to find '+ source +' file.');
            return
       }

       (new Configuration(env, source)).sendBackToMicroServer();


   });

 program.parse(process.argv);
