# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-stretch

    working_directory: ~/zenaton-node

    steps:
      - checkout

      # Build
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Check
      - run:
          name: lint
          command: "./node_modules/.bin/eslint --color ."

      - run:
          name: build
          command: "npm run build"
